/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type ApplicationTransformer from '#transformers/application_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Application = InferData<ApplicationTransformer>
  export namespace Application {
    export type Variants = InferVariants<ApplicationTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
