/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type ApplicationStatusTransitionTransformer from '#transformers/application_status_transition_transformer'
import type ApplicationTransformer from '#transformers/application_transformer'
import type AuthenticatedUserTransformer from '#transformers/authenticated_user_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type ApplicationStatusTransition = InferData<ApplicationStatusTransitionTransformer>
  export namespace ApplicationStatusTransition {
    export type Variants = InferVariants<ApplicationStatusTransitionTransformer>
  }
  export type Application = InferData<ApplicationTransformer>
  export namespace Application {
    export type Variants = InferVariants<ApplicationTransformer>
  }
  export type AuthenticatedUser = InferData<AuthenticatedUserTransformer>
  export namespace AuthenticatedUser {
    export type Variants = InferVariants<AuthenticatedUserTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
