/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ApplicationSchema extends BaseModel {
  static $columns = [
    'amount',
    'assignedReviewerId',
    'attachmentKey',
    'contactEmail',
    'contactName',
    'createdAt',
    'category',
    'id',
    'organizationName',
    'description',
    'title',
    'status',
    'updatedAt',
    'userId',
  ] as const
  $columns = ApplicationSchema.$columns
  @column()
  declare amount: string | null
  @column()
  declare assignedReviewerId: number | null
  @column()
  declare attachmentKey: string | null
  @column()
  declare contactEmail: string | null
  @column()
  declare contactName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare category: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare description: string | null
  @column()
  declare organizationName: string | null
  @column()
  declare title: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class ApplicationAuditLogEntrySchema extends BaseModel {
  static $columns = [
    'applicationId',
    'actorUserId',
    'comment',
    'createdAt',
    'id',
    'nextStatus',
    'previousStatus',
  ] as const
  $columns = ApplicationAuditLogEntrySchema.$columns
  @column()
  declare applicationId: number
  @column()
  declare actorUserId: number
  @column()
  declare comment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nextStatus: string
  @column()
  declare previousStatus: string
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'fullName',
    'id',
    'password',
    'role',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
