/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  ApplicationApprovals: () => import('#controllers/application_approvals_controller'),
  ApplicationChangeRequests: () => import('#controllers/application_change_requests_controller'),
  ApplicationDraftReopenings: () => import('#controllers/application_draft_reopenings_controller'),
  ApplicationOptionSets: () => import('#controllers/application_option_sets_controller'),
  ApplicationRejections: () => import('#controllers/application_rejections_controller'),
  ApplicationReviewStarts: () => import('#controllers/application_review_starts_controller'),
  ApplicationSubmissions: () => import('#controllers/application_submissions_controller'),
  Applications: () => import('#controllers/applications_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  ReviewerApplications: () => import('#controllers/reviewer_applications_controller'),
}
